#!/usr/bin/env bash

changed_files="$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)"

run_if_changed() {
	matches=$(echo "$changed_files" | grep -o "$1" | sort -u | tr '\n' ' ')
	if [ -n "$matches" ]; then echo " * Changes detected in $matches" && echo " * Running $2" && eval "$2"
	fi
}

run_if_changed "composer.json" "sudo -u php-fpm /usr/local/bin/composer update"
run_if_changed "package.json" "(cd ./wp-content/themes/timber-theme && npm prune && npm install)"
run_if_changed "timber-theme/scss/\|timber-theme/js/\|timber-theme/gulpfile.js|.gitignore" "(cd ./wp-content/themes/timber-theme && gulp)"
